"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭](color_bg1)\
[](color_bg1)\
$os\
[](fg:color_bg1 bg:color_aqua)\
[](fg:color_aqua bg:color_blue)\
[](fg:color_blue bg:color_orange)\
$username\
[](bg:color_yellow fg:color_orange)\
[](bg:color_aqua fg:color_yellow)\
[](bg:color_yellow fg:color_aqua)\
$directory\
[](fg:color_yellow bg:color_purple)\
[](fg:color_purple bg:color_red)\
[](fg:color_red bg:color_blue)\
$memory_usage\
[](fg:color_blue bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_purple)\
$docker_context\
$conda\
[](fg:color_purple bg:color_bg1)\
[ ](fg:color_bg1)\
$line_break\
[╰─](color_yellow)\
[](color_yellow)\
[](fg:color_yellow bg:color_yellow)\
[](fg:color_yellow bg:color_red)\
[](fg:color_red bg:color_aqua)\
[](fg:color_aqua bg:color_purple)\
[ ](fg:color_purple)\
"""

right_format = """
[](color_bg1)\
$time
[ ](fg:color_bg1)\
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#ffffff'
color_bg1 = '5'
color_bg3 = '8'
color_blue = '10'
color_aqua = '12'
color_green = '13'
color_orange = '4'
color_purple = '7'
color_red = '2'
color_yellow = '3'

[os]
disabled = false
style = "bg:color_bg1 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = " "
openSUSE = " "
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CachyOS = "󰍲 "
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Unknown = "?"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
format = '[$ssh_symbol](fg:color_fg0 bg:color_orange)[$hostname](fg:color_fg0 bg:color_orange)'
trim_at = '.companyname.com'
disabled = false

[localip]
ssh_only = false
format = '[ $localipv4 ](fg:color_fg0 bg:color_yellow)'
disabled = false

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = "bg:color_blue"
format = '[$symbol [${ram} ](fg:color_fg0 bg:color_blue)]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Dokumenty" = "󰈙 "
"Pobrane" = " "
"Muzyka" = "󰝚 "
"Obrazy" = " "
".config" = " "
"moje" = "󱙧 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_purple"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
